version: '3.8'

services:
   web:
       build: ./
       command: python manage.py runserver 0.0.0.0:8000
       volumes:
        - ./image_analyzer:/usr/src/image_analyzer
       ports:
        - 8000:8000
  
